name: Vercel Deploy Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
run-name: ${{ github.actor }} is deploying site to Vercel  🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Check Node Version
        run: node --version
      - name: Install Vercel CLI
        run: npm install --global vercel@latest pnpm
      - name: Install Deps
        run: pnpm install
      - name: Check out Markdown repo
        # https://github.com/actions/checkout
        uses: actions/checkout@master
        with:
          repository: CoyoteWaltz/MarkdownNotes
          ref: "master"
          fetch-depth: 0 # all history
          token: ${{ secrets.PAT_TOKEN }}
          path: "./temp"
      - name: List Files
        run: |
          ls ${{ github.workspace }}
      - name: Build Content Layout
        run: pnpm run build:layout
      - name: Push Commit For New Pages
        run: |
          git config user.name vercel-deploy-actions
          git config user.email coyote_waltz@163.com
          git add .
          # git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          git commit --allow-empty -m "ci: sync markdown after run layout [skip actions]" --no-verify
          git push
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
