name: Vercel Deploy Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
run-name: ${{ github.actor }} is deploying site to Vercel  🚀
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Check Node Version
        run: node --version
      - name: Install Vercel CLI
        run: npm install --global vercel@latest pnpm
      - name: Install Deps
        run: pnpm install
      - name: Check out Markdown repo
        uses: actions/checkout@master
        with:
          repository: CoyoteWaltz/MarkdownNotes
          token: ${{ secrets.PAT_TOKEN }}
          path: "./temp"
      - name: List Files
        run: |
          ls ${{ github.workspace }}
      - name: Build Content Layout
        run: pnpm run build:layout
      - name: Build Content Layout
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "ci: sync markdown after run layout"
          git push
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
